[package]
name = "firewall"
version = "0.1.0"
authors = ["valentin"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cargo-bpf = "1.2.0"
